imports:
    - { resource: services/commands.yaml }
    - { resource: services/commands_installer.yaml }
    - { resource: services/installer.yaml }
    - { resource: services/installer_requirements.yaml }
    - { resource: services/fixtures_factories.yaml }
    - { resource: services/fixtures_listeners.yaml }
    - { resource: services/fixtures.yaml }

parameters:
    test_parameter: 'TEST'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

