services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Vankosoft\ApplicationBundle\Controller\SettingsController:
        tags: ['controller.service_arguments']
        autowire: true
        calls:
            - setThemeRepository: ['@sylius.repository.theme']
            
#     Vankosoft\ApplicationBundle\Controller\:
#         resource: '../../Controller/'
#         tags: ['controller.service_arguments', 'container.service_locator']
        
    Vankosoft\ApplicationBundle\Controller\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        
    Vankosoft\ApplicationBundle\Controller\DashboardController:
        tags: ['controller.service_arguments']
        autowire: true
    
    Vankosoft\ApplicationBundle\Controller\ApplicationExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.repository.application'
            - '@vs_application.factory.application'
            
    Vankosoft\ApplicationBundle\Controller\SettingsExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_app.settings_manager'
            - '@vs_application.repository.application'
            - '@vs_application.repository.settings'
            - '@vs_application.factory.settings'
            - '@vs_application.repository.taxonomy'
        
    Vankosoft\ApplicationBundle\Controller\TaxonomyTaxonsController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.repository.taxonomy'
            - '@vs_application.repository.taxon'

