services:
    vs_application.resources.application.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\ApplicationForm
        tags:
            - { name: form.type }
        arguments: ['%vs_application.model.application.class%']

    vs_application.resources.settings.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\SettingsForm
        tags:
            - { name: form.type }
        arguments: ['%vs_application.model.settings.class%', '%vs_cms.model.pages.class%']

    vs_application.resources.taxonomy.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\TaxonomyForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_application.model.taxonomy.class%'
            - '@vs_application.repository.locale'
            - "@request_stack"
        
    vs_application.resources.taxon.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\TaxonForm
        tags:
            - { name: form.type }
        arguments: ['%vs_application.model.taxon.class%']
        
    vs_application.resources.locale.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\LocaleForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_application.model.locale.class%'
            - '@vs_application.repository.locale'
            - "@request_stack"
            
    vs_application.resources.cookie_consent_translation.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\CookieConsentTranslationForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_application.model.cookie_consent_translation.class%'
            - '@vs_application.repository.locale'
            
    vs_application.resources.tags_whitelist_context.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\TagsWhitelistContextForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_application.model.tags_whitelist_context.class%'
            
    vs_application.resources.widget.form:
        class: Vankosoft\PaymentBundle\Form\ProductForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_payment.model.product.class%'
            - '@request_stack'
            - '@vs_application.repository.locale'
            - '%vs_payment.model.product_category.class%'
            - '%vs_payment.model.currency.class%'
