services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_app.listener.theme_change:
        class: Vankosoft\ApplicationBundle\EventListener\ThemeChangeListener
        arguments:
            - '@sylius.theme.context.settable'
            - '@sylius.repository.theme'
            - '@vs_application.repository.settings'
            - '%vs_application.settings.application_id%'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
