vs_users_crud:
    resource: |
        alias: vs_users.users
        path: /users
        templates: "@VSUsers/UsersCrud"
    type: sylius.resource
    options:
        expose: true
        
vs_users_user_roles:
    resource: |
        alias: vs_users.user_roles
        path: /user-roles
        templates: "@VSUsers/UsersRoles"
    type: sylius.resource

vs_users_roles_tree_combo_with_selected:
    path: /json/{currentUserId}-{editUserId}/user-roles-collection/easyui-combotree
    controller: Vankosoft\UsersBundle\Controller\UsersExtController::rolesEasyuiComboTreeWithSelectedSource
    
vs_users_roles_collection_parent_tree_combo_with_selected:
    path: /json/{roleId}/user-roles-collection-parent/easyui-combotree
    controller: Vankosoft\UsersBundle\Controller\UsersRolesExtController::rolesEasyuiComboTreeWithSelectedSource
