imports:
    - { resource: 'fixtures/application_configuration.yaml' }
    - { resource: 'fixtures/sample_data.yaml' }
    
    #- { resource: '@SyliusCoreBundle/Resources/config/app/fixtures/tshirt.yaml' }
    #- { resource: '@SyliusCoreBundle/Resources/config/app/fixtures/custom_fixtures.yaml' }

parameters:
    env(SYLIUS_FIXTURES_HOSTNAME): 'localhost'
    env(SYLIUS_FIXTURES_THEME_NAME): ~
