ia_cms_taxonomy_vocabularies:
    resource: |
        alias: ia_cms.taxonomy_vocabularies
        except: ['show']
        path: /vocabularies
        templates: "IACmsBundle:TaxonomyVocabularies"
    type: sylius.resource

ia_cms_taxonomy_vocabularies_update:
    path: /vocabularies/{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: ia_cms.controller.taxonomy_vocabularies:updateAction
        _sylius:
            template: IACmsBundle:TaxonomyVocabularies:update.html.twig

ia_cms_taxonomy_vocabulary_terms:
    path: /vocabularies/{id}/terms
    controller: IA\CmsBundle\Controller\TaxonomyTermsController::terms
